import Head from "next/head";
import {
  type InferGetServerSidePropsType,
  type GetServerSideProps,
} from "next";
import AuthButton from "../../components/feature/auth/AuthButton";
import { getSession } from "next-auth/react";
import Image from "next/image";

export default function Welcome({}: InferGetServerSidePropsType<
  typeof getServerSideProps
>) {
  return (
    <>
      <Head>
        <title>Mocka</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center  bg-black antialiased">
        <div className="container relative flex max-w-lg flex-col items-center justify-center gap-12 px-4 py-16 md:max-w-3xl">
          <Image
            className="mt-24"
            src="/assets/logo.png"
            width={90}
            height={90}
            alt=""
          />
          <span className=" absolute left-10 text-2xl md:left-10 md:top-5 md:text-5xl">
            {/* <Image src="/assets/logo.png" width={50} height={50} alt="" /> */}
          </span>
          <h1 className="text-center text-5xl font-extrabold leading-snug tracking-tight text-white md:text-[5rem]">
            Spend Valuable Time In{" "}
            <span className="underline decoration-green-200 decoration-2 underline-offset-8">
              Mocka
            </span>
          </h1>

          <div className="flex flex-col items-center gap-2">
            <AuthButton />
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
